### ISSUE TITLE
Control text file encoding (UTF-16)

### ISSUE THREAD

**Issue by dragonshardz** [PacoHobi/CurrentSong#7]
Hi, I'd like to be able to set the encoding of the text file - I use CurrentSong's output to list the currently playing song through Rainmeter which doesn't read unicode character properly from UTF-8 encoding.

Would it be possible to have the text file be able to be output as either UTF-16 or UTF-8?

**Comment by PacoHobi** [comment]
Hi @dragonshardz, I added the option to choose the text file encoding. According to this [Rainmeter page](http://docs.rainmeter.net/tips/unicode-in-rainmeter) you will need to use the `UTF-16LE` encoding.

Please tell me here if it works for you.

*To install the new version [click here](https://github.com/PacoHobi/CurrentSong/releases/download/v1.2/currentsong.xpi)*

**Comment by dragonshardz** [comment]
Thank you very much, @PacoHobi. It's writing the text file properly, and it does seem to be in UTF-16LE. For some reason Rainmeter - or rather the lua script that is reading the file - doesn't quite seem to be reading it properly. I'll have to keep poking at it.

**Comment by PacoHobi** [comment]
When I open the saved text file in Notepad++ it says it's encoded in  `UCS-2 LE w/o BOM`. If I then go to *Encoding > Encode in UCS-2 Little Endian*, the encoding changes to `UCS-2 Little Endian`, which is what [this page](http://docs.rainmeter.net/tips/unicode-in-rainmeter) actually asks for.

So maybe the problem is with not having BOM. You could you test if that is the case and I will see what I can do.
